version: '3.8'

services:
  flask-backend:
    build: ./flask-backend
    container_name: flask-app
    ports:
      - "5000:5000"
    restart: always

  express-frontend:
    build: ./express-frontend
    container_name: express-app
    ports:
      - "3000:3000"
    restart: always
